name: Python test

on: [push]

jobs:
  python-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install ninja for JIT compiler
      run: |
        pip install ninja
    - name: Benchmark function with JIT compiler
      run: |
        python test/benchmark.py splatting_function
    - name: Build cpp extension
      run: |
        pip install -e .
    - name: Install pytest
      run: |
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest test
    - name: Benchmark compiled cpp function
      run: |
        python test/benchmark.py splatting_cpp
    - name: Benchmark function
      run: |
        python test/benchmark.py splatting_function
    - name: Benchmark module
      run: |
        python test/benchmark.py splatting_module        
