name: Test

on: [push, pull_request]

jobs:
  Benchmark:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install ninja

    - name: JIT compile extension
      run: |
        python -c "import splatting"

    - name: Benchmark JIT compiled splatting.SummationSplattingFunction
      run: |
        python test/benchmark.py splatting_function

    - name: Build cpp extension
      run: |
        python -m pip install -e .

    - name: Benchmark splatting.cpu.splatting_forward and splatting.cpu.splatting_backward
      run: |
        python test/benchmark.py splatting_cpu
    - name: Benchmark splatting.SummationSplattingFunction
      run: |
        python test/benchmark.py splatting_function
    - name: Benchmark splatting.splatting_function summation
      run: |
        python test/benchmark.py splatting_function_summation
    - name: Benchmark splatting.Splatting module summation
      run: |
        python test/benchmark.py splatting_module_summation
    - name: Benchmark splatting.Splatting module softmax
      run: |
        python test/benchmark.py splatting_module_softmax

  Lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade pre-commit
        pre-commit install

    - name: Lint
      run: pre-commit run --all-files --show-diff-on-failure

  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -r requirements_test.txt

    - name: JIT compile extension
      run: |
        python -c "import splatting"

    - name: Test JIT compiled extension with pytest
      run: |
        coverage run --parallel-mode -m pytest test -cov=./splatting --cov-config=.coveragerc

    - name: Build cpp extension
      run: |
        python -m pip install -e .

    - name: Test compiled extension with pytest
      run: |
        coverage run --parallel-mode -m pytest test -cov=./splatting --cov-config=.coveragerc
    - name: Combine coverage
      run: |
        coverage combine
        coverage xml

    - name: Upload to Coveralls.io
      run: |
        coveralls
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.xml # optional
        fail_ci_if_error: true # optional (default = false)
