name: Python test

on: [push]

jobs:
  python-jit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install ninja for JIT compiler
      run: |
        pip install ninja
    - name: Benchmark function with JIT compiler
      run: |
        python test/benchmark.py splatting_function

  python-cpp:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build cpp extension
      run: |
        pip install -e .
    - name: Install pytest
      run: |
        pip install pytest
    - name: Test with pytest
      run: |
        python -m pytest test
    - name: Benchmark splatting_cpp.splatting_forward and splatting_cpp.splatting_backward
      run: |
        python test/benchmark.py splatting_cpp
    - name: Benchmark splatting.SummationSplattingFunction
      run: |
        python test/benchmark.py splatting_function
    - name: Benchmark splatting.splatting_function summation
      run: |
        python test/benchmark.py splatting_function_summation
    - name: Benchmark splatting.Splatting module summation
      run: |
        python test/benchmark.py splatting_module_summation
    - name: Benchmark splatting.Splatting module softmax
      run: |
        python test/benchmark.py splatting_module_softmax
