name: Python test

on: [push]

jobs:
  python-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install package and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build package
      run: |
        pip install -e .
    - name: Install build dependencies
      run: |
        pip install -e '.[test]'
    - name: Test with pytest
      run: |
        python -m pytest test
